//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESports.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogador
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Elo { get; set; }
        public Lane Lane { get; set; }
        public Nullable<int> TimeId { get; set; }
    
        public virtual Time Time { get; set; }
    }
}
