//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESports.Models
{
    using System;
    
    public enum Lane : int
    {
        Mid = 0,
        Top = 1,
        Adc = 2,
        Suporte = 3,
        Jungle = 4
    }
}
