//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioJulia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Melhoria
    {
        public int Id { get; set; }
        public string Texto { get; set; }
        public bool Possivel { get; set; }
    
        public virtual Registro Registro { get; set; }
    }
}
