//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioJulia
{
    using System;
    
    public enum Nota : int
    {
        Um = 1,
        Dois = 2,
        Tres = 3,
        Quatro = 4,
        Cinco = 5
    }
}
