//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioJulia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personagem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personagem()
        {
            this.Registro_Personagem = new HashSet<Registro_Personagem>();
        }
    
        public int Id { get; set; }
        public string GrauParentesco { get; set; }
        public Nullable<int> Idade { get; set; }
        public Nota Nota { get; set; }
        public string Nome { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro_Personagem> Registro_Personagem { get; set; }
    }
}
