//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiarioJulia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_Personagem
    {
        public int Id { get; set; }
        public Nullable<int> PersonagemId { get; set; }
        public int RegistroId { get; set; }
    
        public virtual Personagem Personagem { get; set; }
        public virtual Registro Registro { get; set; }
    }
}
